@baseUrl = http://localhost:4004/odata/v4/hospital

### GET all Departments
GET {{baseUrl}}/Departments

### Get all doctors
GET {{baseUrl}}/Doctors

### GET all patients
GET {{baseUrl}}/Patients

### GET all appointments
GET {{baseUrl}}/Appointments

### Get all Medical Records
GET {{baseUrl}}/MedicalRecords

### GET all doctors filtered by specialization

GET {{baseUrl}}/Doctors?$filter=specialization eq 'Cardiologist'

### GET appointments for a specific date

GET {{baseUrl}}/Appointments?$filter=appointmentDate eq 2026-06-01


### POST a new patient
POST {{baseUrl}}/Patients
Content-Type: application/json

{
    "firstName":"Karan without",
    "lastName":"Patel",
    "dateOfBirth":"2000-05-10",
    "gender":"Male",
    "bloodGroup":"A_POS",
    "phone":"9877009999",
    "email":"karan@gmail.com",
    "address":"Mumbai",
    "emergencyContact":"9878009999",
    "registrationDate":"2026-06-01"
}

### POST a new appointment
POST {{baseUrl}}/Appointments
Content-Type: application/json

{
    "patientId":"p9999999-9999-9999-9999-999999999999",
    "doctorId":"d1111111-1111-1111-1111-111111111111",
    "appointmentDate":"2026-06-10",
    "appointmentTime":"10:00:00",
    "status":"Scheduled",
    "reason":"General Checkup",
    "notes":"First Visit",
    "fee":1000
}

### GET patients filtered by blood group
GET {{baseUrl}}/Patients?$filter=bloodGroup eq 'O_POS'

### PATCH appointment status to Completed
PATCH {{baseUrl}}/Appointments(a3333333-3333-3333-3333-333333333333)
Content-Type: application/json

{
    "status":"Completed"
}